### ISSUE TITLE
Stop recording on silence

### ISSUE THREAD

**Issue by Ajaxy** [mattdiamond/Recorderjs#102]
Thank you for this tool.
I'd like to know is it possible somehow to automatically stop recording when user stops talking? The same as that Siri app does.

**Comment by b-d-b** [comment]
This app does not support that functionality.  You would have to build out that functionality.  Look through the library and see if you think it's possible -- most likely you will need to constantly export the WAV file and check the bits against some algorithm to see what the decibel levels are and then stop the recording.  Certainly possible, but would require some ingenuity on your part.

**Comment by Ajaxy** [comment]
Guess that should be easier. I.e. there is !(https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode.frequencyBinCount). Thank you, I'll try to dig in and come up with code.

**Comment by TheJimFactor** [comment]
I customized recorder.js to automatically stop after some silence. If people are interested I can try and clena it up for a pull request or make a fork.

**Comment by playma** [comment]
@TheJimFactor I am interested in it. Can you help me?
