### ISSUE TITLE
The sample not working

### ISSUE THREAD

**Issue by carlos-proenca** [mattdiamond/Recorderjs#113]
![error](https://cloud.githubusercontent.com/assets/7811445/7384474/5bcc88ac-ee0a-11e4-8045-52377de3548e.jpg)

**Comment by notthetup** [comment]
I believe for `getUserMedia` to work properly you need to server the html file over http and not just open it using the `file:///` protocol

**Comment by carlos-proenca** [comment]
yes, you right my problems is on wordpress.
thks for all.
