### ISSUE TITLE
How to recored output sound of computer/web?

### ISSUE THREAD

**Issue by shivrajsa** [mattdiamond/Recorderjs#145]
Is it possible to record the output sound we get from computer.
Or 
I have music web application where we can write & play notations in browser. Is it possible to record output sound created by web using this lib? 

I think we just need to set set source as 'computer output', but I am not getting how to set that.

**Comment by mattdiamond** [comment]
The web audio API has no way to process audio from outside the web browser. For in-browser sources of audio, such as `<audio>` and `<video>` elements, you can create a [MediaElementAudioSourceNode](http://www.w3.org/TR/webaudio/#MediaElementAudioSourceNode) and route that to RecorderJS.

**Comment by shivrajsa** [comment]
Actually I am not using <audio> or <video> tag, I have developed an application using MIDI.js where user can write & play his music. So I want to give a capability to user to export music created by him. So I was thinking if I can give option to record music while playing using Recorder.js. Is it possible?
