### ISSUE TITLE
Multiple recording in firefox works only 1-2 times

### ISSUE THREAD

**Issue by wurstbrot** [mattdiamond/Recorderjs#149]
In chrome, everything works fine.
In firefox I can use the recording only one or two times. Sometimes it stops the recording in the middle of the second/third one.
The recording time seems to be correct, but when I play it, it is quite.
I guess, that firefox is not releasing/deleting the old record(s).
In my stopRecording method, I use:
    recorder.stop(); //[...]
    recorder.clear();

Before I start a new recording, I use:
    window.URL.revokeObjectURL(audioUrl);

You can test it here https://audio.timo-pagel.de/l/
Do I miss something?

**Comment by sergey-serebryakov** [comment]
I observe the same behavior. The quick workaround is to re-create Recorder each time (each time allowing browser to use mic).

**Comment by ShiYw** [comment]
I've run into the same problem before.
No idea.Good luck.

**Comment by wurstbrot** [comment]
I moved to RecordRTC now. See https://www.webrtc-experiment.com/RecordRTC/ . There it is working multiple times.
