### ISSUE TITLE
Changing bit depth to 16-bit WAV

### ISSUE THREAD

**Issue by skunkwerk** [mattdiamond/Recorderjs#155]
Where would I modify the code to support output of 16-bit WAV files, instead of 32-bit?

Doesn't the line following [this one](https://github.com/mattdiamond/Recorderjs/blob/master/src/recorder.js#L179) set it to 16-bits per sample?
Unlike [this issue](https://github.com/mattdiamond/Recorderjs/issues/11), I'm not concerned with the sample rate or number of channels.

**Comment by ohtangza** [comment]
I think, you could see floatTo16BitPCM() function (https://github.com/mattdiamond/Recorderjs/blob/master/src/recorder.js) with small header change as well.

As the name suggested, isn't it already 16bit PCM encoded data?
(of course, stereo makes id 32bit per samples)

**Comment by skunkwerk** [comment]
Yup, I just saw that code.  I was opening the files in Audacity, which was somehow automatically converting them to 32-bit.  But in VLC's media information dialog, it is indeed 16-bit.  Sorry about this.

**Comment by ohtangza** [comment]
No problem. Good to hear that your issue has been resolved.
