### ISSUE TITLE
No sound, empty exported wav, no errors.

### ISSUE THREAD

**Issue by octatone** [mattdiamond/Recorderjs#22]
Seems that this library is broken for now.

26.0.1410.65, Mac 10.7, chrome://flags audio input enabled

Looking at the exported file in a text editor shows what looks like a  header section and then all zeroes.

Speech API works fine so I know it's not an issue with my microphone or input setup.

**Comment by cmartinez84** [comment]
Possibly not the correct answer, but I just spent a few hours trying to figure out why I, too, was being returned an empty wav. It turns out I never actually called the record method on my recorder. I forgot my parentheses. Calling rec.exportWAV() can return back an empty wav with no errors.
