### ISSUE TITLE
Why are we recording in stereo?

### ISSUE THREAD

**Issue by MarkIvanowich** [mattdiamond/Recorderjs#82]
Most microphones are mono devices, why are we recording two channels, and then having to hassle with interleaving them? Wouldn't mono result in half a file size (header data excluded)?
Is there any benefit to having multiple channels?

**Comment by qrpike** [comment]
+1 to mono

**Comment by agrueneberg** [comment]
I submitted a pull request a while ago: https://github.com/mattdiamond/Recorderjs/pull/36
